# Generated by Django 4.2.2 on 2023-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsquestion',
            name='question_type',
            field=models.CharField(choices=[('1', 'Logic'), ('2', 'Sense')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='responsresult',
            name='logic',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='responsresult',
            name='sense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thinkquestion',
            name='question_type',
            field=models.CharField(choices=[('1', 'Must'), ('2', 'Want')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thinkresult',
            name='must',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='thinkresult',
            name='want',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
