# Generated by Django 4.2.2 on 2023-09-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0002_alter_responsquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsresult',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thinkresult',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
