# Generated by Django 4.2.2 on 2023-10-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0005_rename_a1_content_mandarabase_a1_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandarabase',
            name='end_YYYYMM',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='mandarabase',
            name='start_YYYYMM',
            field=models.CharField(max_length=6),
        ),
        migrations.AddConstraint(
            model_name='mandarabase',
            constraint=models.UniqueConstraint(fields=('user_id', 'company_id', 'start_YYYYMM', 'end_YYYYMM'), name='unique_mandara'),
        ),
    ]
