# Generated by Django 4.2.2 on 2023-10-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0006_alter_mandarabase_end_yyyymm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandaraprogress',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='mandaraprogress',
            constraint=models.UniqueConstraint(fields=('mandara_base_id', 'date'), name='unique_mandara_progress'),
        ),
    ]
