# Generated by Django 4.2.2 on 2023-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0009_alter_user_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(blank=True, choices=[(99, '日々研'), (40, 'Partner'), (30, 'Company Admin'), (20, 'Company Super Visor'), (10, 'Company Staff')], default=99, null=True),
        ),
    ]
