# Generated by Django 4.2.2 on 2023-12-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0011_alter_user_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
