# Generated by Django 4.2.2 on 2023-12-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0012_company_created_by_user_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonknowevaluationperiod',
            options={'verbose_name': 'BONKNOW 評価期間', 'verbose_name_plural': 'BONKNOW 評価期間'},
        ),
        migrations.AlterModelOptions(
            name='selfcheckevaluationperiod',
            options={'verbose_name': 'SELFCHECK 評価期間', 'verbose_name_plural': 'SELFCHECK 評価期間'},
        ),
        migrations.AlterField(
            model_name='bonknowevaluationperiod',
            name='evaluation_end',
            field=models.DateField(blank=True, null=True, verbose_name='評価終了時間'),
        ),
        migrations.AlterField(
            model_name='bonknowevaluationperiod',
            name='evaluation_name',
            field=models.CharField(max_length=255, verbose_name='評価名'),
        ),
        migrations.AlterField(
            model_name='bonknowevaluationperiod',
            name='evaluation_start',
            field=models.DateField(blank=True, null=True, verbose_name='評価開始時間'),
        ),
        migrations.AlterField(
            model_name='bonknowevaluationperiod',
            name='respons_questions',
            field=models.ManyToManyField(blank=True, related_name='bonknow_evaluation_periods', to='hibiLaboSystem.responsquestion', verbose_name='RESPONS質問'),
        ),
        migrations.AlterField(
            model_name='bonknowevaluationperiod',
            name='think_questions',
            field=models.ManyToManyField(blank=True, related_name='bonknow_evaluation_periods', to='hibiLaboSystem.thinkquestion', verbose_name='THINK質問'),
        ),
        migrations.AlterField(
            model_name='selfcheckevaluationperiod',
            name='evaluation_end',
            field=models.DateField(blank=True, null=True, verbose_name='評価終了時間'),
        ),
        migrations.AlterField(
            model_name='selfcheckevaluationperiod',
            name='evaluation_name',
            field=models.CharField(max_length=255, verbose_name='評価名'),
        ),
        migrations.AlterField(
            model_name='selfcheckevaluationperiod',
            name='evaluation_start',
            field=models.DateField(blank=True, null=True, verbose_name='評価開始時間'),
        ),
        migrations.AlterField(
            model_name='selfcheckevaluationperiod',
            name='selfcheck_questions',
            field=models.ManyToManyField(blank=True, related_name='selfcheck_evaluation_periods', to='hibiLaboSystem.selfcheckquestion', verbose_name='SELFCHECK質問'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='hibiLaboSystem.branch', verbose_name='支店'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='hibiLaboSystem.company', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(blank=True, choices=[(99, '日々研'), (40, 'Partner'), (30, 'Company Admin'), (20, 'Company Super Visor'), (10, 'Company Staff')], null=True, verbose_name='役割'),
        ),
    ]
