# Generated by Django 5.0 on 2023-12-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0014_mandaraperiod_remove_mandarabase_unique_mandara_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandaraperiod',
            options={'verbose_name': 'MANDARA 評価期間', 'verbose_name_plural': 'MANDARA 評価期間'},
        ),
        migrations.AlterModelTable(
            name='mandaraperiod',
            table='mandara_periods',
        ),
    ]
