# Generated by Django 4.2.2 on 2023-12-26 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0015_alter_mandaraperiod_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatasheetEvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_name', models.CharField(max_length=255, verbose_name='評価名')),
                ('evaluation_start', models.DateField(blank=True, null=True, verbose_name='評価開始時間')),
                ('evaluation_end', models.DateField(blank=True, null=True, verbose_name='評価終了時間')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_evaluation_periods', to='hibiLaboSystem.company')),
            ],
            options={
                'verbose_name': 'WATASHEET 評価期間',
                'verbose_name_plural': 'WATASHEET 評価期間',
                'db_table': 'watasheet_evaluation_periods',
            },
        ),
        migrations.CreateModel(
            name='WatasheetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('sort_no', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, null=True, verbose_name='カルテット分布')),
            ],
            options={
                'db_table': 'watasheet_questions',
            },
        ),
        migrations.AlterField(
            model_name='mandaraperiod',
            name='end_date',
            field=models.DateField(verbose_name='評価終了時間'),
        ),
        migrations.AlterField(
            model_name='mandaraperiod',
            name='start_date',
            field=models.DateField(verbose_name='評価開始時間'),
        ),
        migrations.CreateModel(
            name='WatasheetTypeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watasheet_type_a', models.IntegerField(blank=True, null=True)),
                ('watasheet_type_b', models.IntegerField(blank=True, null=True)),
                ('watasheet_type_c', models.IntegerField(blank=True, null=True)),
                ('watasheet_type_d', models.IntegerField(blank=True, null=True)),
                ('watasheet_type_e', models.IntegerField(blank=True, null=True)),
                ('watasheet_type_f', models.IntegerField(blank=True, null=True)),
                ('flg_finished', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_type_results', to='hibiLaboSystem.company')),
                ('evaluation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_type_results', to='hibiLaboSystem.watasheetevaluationperiod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_type_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watasheet_type_results',
            },
        ),
        migrations.CreateModel(
            name='WatasheetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_results', to='hibiLaboSystem.company')),
                ('evaluation_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_results', to='hibiLaboSystem.watasheetevaluationperiod')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watasheet_results', to=settings.AUTH_USER_MODEL)),
                ('watasheet_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_results', to='hibiLaboSystem.watasheetquestion')),
            ],
            options={
                'db_table': 'watasheet_answer_results',
            },
        ),
        migrations.AddField(
            model_name='watasheetevaluationperiod',
            name='watasheet_questions',
            field=models.ManyToManyField(blank=True, related_name='watasheet_evaluation_periods', to='hibiLaboSystem.watasheetquestion', verbose_name='WATASHEET質問'),
        ),
    ]
