# Generated by Django 4.2.2 on 2023-12-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0016_alter_mandaraperiod_end_date_and_more'),
        ('hibiLaboSystem', '0016_watasheetevaluationperiod_watasheetquestion_and_more'),
    ]

    operations = [
    ]
