# Generated by Django 5.0 on 2023-12-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0017_merge_20231227_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='watasheettyperesult',
            name='watasheet_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
