# Generated by Django 4.2.2 on 2024-01-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0018_watasheettyperesult_watasheet_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='watasheettyperesult',
            name='concept_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='concept_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='concept_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='development_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='development_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='development_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='dwt_go_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='dwt_go_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='dwt_go_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='dwt_think_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='dwt_think_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='dwt_think_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='economy_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='economy_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='economy_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='etc_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='etc_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='etc_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='family_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='family_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='family_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='fw_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='fw_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='fw_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='fw_job_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='fw_job_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='fw_job_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='happiness_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='happiness_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='happiness_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='health_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='health_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='health_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='hobby_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='hobby_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='hobby_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='human_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='human_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='human_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='inportant_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='inportant_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='inportant_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='keyword_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='keyword_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='keyword_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='kw_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='kw_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='kw_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='kw_job_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='kw_job_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='kw_job_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='mission_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='mission_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='mission_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_happiness_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_happiness_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_happiness_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_inportant_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_inportant_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_inportant_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_want_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_want_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='n_want_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='rule_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='rule_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='rule_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='vision_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='vision_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='vision_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='w_want_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='w_want_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='w_want_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='want_1st',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='want_2nd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='want_3rd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='work_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='work_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='work_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_0_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_10_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_20_30',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_30_40',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_40_50',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_50_70',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='years_old_70_100',
            field=models.TextField(blank=True, null=True),
        ),
    ]
