# Generated by Django 4.2.2 on 2024-01-16 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0019_watasheettyperesult_concept_1st_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonknowevaluationperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonknow_evaluation_periods', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='honneanswerresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='honneanswerresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_answer_results', to='hibiLaboSystem.honneevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='honneanswerresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='honneevaluationperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_evaluation_periods', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='honneindexresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_index_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='honneindexresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_index_results', to='hibiLaboSystem.honneevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='honneindexresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_index_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='honnetyperesult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_type_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='honnetyperesult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_type_results', to='hibiLaboSystem.honneevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='honnetyperesult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honne_type_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mandarabase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandara_base', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='mandarabase',
            name='mandara_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandara_base', to='hibiLaboSystem.mandaraperiod'),
        ),
        migrations.AlterField(
            model_name='mandarabase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandara_base', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mandaraperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandara_periods', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='mandaraprogress',
            name='mandara_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandara_progress', to='hibiLaboSystem.mandarabase'),
        ),
        migrations.AlterField(
            model_name='responsanswer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respons_answers', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='responsanswer',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respons_answers', to='hibiLaboSystem.bonknowevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='responsanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respons_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respons_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='responsresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respons_results', to='hibiLaboSystem.bonknowevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='responsresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respons_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selfcheckanswerresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='selfcheckanswerresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_answer_results', to='hibiLaboSystem.selfcheckevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='selfcheckanswerresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selfcheckevaluationperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_evaluation_periods', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='selfcheckindexresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_index_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='selfcheckindexresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_index_results', to='hibiLaboSystem.selfcheckevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='selfcheckindexresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_index_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selfchecktyperesult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_type_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='selfchecktyperesult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_type_results', to='hibiLaboSystem.selfcheckevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='selfchecktyperesult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selfcheck_type_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thinkanswer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='think_answers', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='thinkanswer',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='think_answers', to='hibiLaboSystem.bonknowevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='thinkanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='think_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thinkresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='think_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='thinkresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='think_results', to='hibiLaboSystem.bonknowevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='thinkresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='think_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watasheetresult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='watasheetresult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_results', to='hibiLaboSystem.watasheetevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='watasheetresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watasheettyperesult',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_type_results', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='watasheettyperesult',
            name='evaluation_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_type_results', to='hibiLaboSystem.watasheetevaluationperiod'),
        ),
        migrations.AlterField(
            model_name='watasheettyperesult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_type_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
