# Generated by Django 4.2.2 on 2024-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0021_company_visble_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='visble_flag',
            field=models.BooleanField(blank=True, default=False, verbose_name='HONNE社員名表示'),
        ),
    ]
