# Generated by Django 5.0.1 on 2024-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0022_alter_company_visble_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsresult',
            name='flg_finished',
            field=models.BooleanField(default=False),
        ),
    ]
