# Generated by Django 5.0.1 on 2024-02-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0023_responsresult_flg_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_action_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_action_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_action_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_concept_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_mission_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_mission_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_mission_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_values_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_values_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_values_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_vision_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_vision_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_vision_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
