# Generated by Django 5.0.1 on 2024-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0024_watasheettyperesult_team_action_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_vision_10_years',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_vision_1_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='team_vision_5_years',
            field=models.TextField(blank=True, null=True),
        ),
    ]
