# Generated by Django 5.0.1 on 2024-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0026_watasheettyperesult_team_action_10_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_action_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_action_10',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_action_10_years',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_action_1_year',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_action_5',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_action_5_years',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_concept_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_mission_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_mission_2',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_mission_3',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_values_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_values_2',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_values_3',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_vision_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_vision_10',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_vision_10_years',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_vision_1_year',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_vision_5',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='team_vision_5_years',
        ),
        migrations.AddField(
            model_name='company',
            name='team_action_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_action_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_action_10_years',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_action_1_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_action_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_action_5_years',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_concept_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_mission_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_mission_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_mission_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_values_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_values_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_values_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_vision_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_vision_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_vision_10_years',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_vision_1_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_vision_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='team_vision_5_years',
            field=models.TextField(blank=True, null=True),
        ),
    ]
