# Generated by Django 5.0.1 on 2024-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0027_remove_watasheettyperesult_team_action_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watasheettyperesult',
            name='vision_10_years',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='vision_1_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='vision_5_years',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_1',
            field=models.TextField(blank=True, null=True, verbose_name='Content 1 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_10',
            field=models.TextField(blank=True, null=True, verbose_name='Content 10 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_10_years',
            field=models.TextField(blank=True, null=True, verbose_name='10 year late (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_1_year',
            field=models.TextField(blank=True, null=True, verbose_name='1 year late (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_5',
            field=models.TextField(blank=True, null=True, verbose_name='Content 5 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_5_years',
            field=models.TextField(blank=True, null=True, verbose_name='5 year late (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_concept_1',
            field=models.TextField(blank=True, null=True, verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_1',
            field=models.TextField(blank=True, null=True, verbose_name='Content 1 (MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_2',
            field=models.TextField(blank=True, null=True, verbose_name='Content 2 (MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_3',
            field=models.TextField(blank=True, null=True, verbose_name='Content 3 (MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_1',
            field=models.TextField(blank=True, null=True, verbose_name='Content 1 (VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_2',
            field=models.TextField(blank=True, null=True, verbose_name='Content 2 (VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_3',
            field=models.TextField(blank=True, null=True, verbose_name='Content 3 (VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1',
            field=models.TextField(blank=True, null=True, verbose_name='Content 1 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10',
            field=models.TextField(blank=True, null=True, verbose_name='Content 10 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10_years',
            field=models.TextField(blank=True, null=True, verbose_name='10 years late (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1_year',
            field=models.TextField(blank=True, null=True, verbose_name='1 year late (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5',
            field=models.TextField(blank=True, null=True, verbose_name='Content 5 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5_years',
            field=models.TextField(blank=True, null=True, verbose_name='5 years late (VISION)'),
        ),
    ]
