# Generated by Django 5.0.1 on 2024-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0028_watasheettyperesult_vision_10_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='team_action_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_10',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 10 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_10_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10年後 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_1_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1年後 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_5',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 5 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_5_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5年後 (ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 10 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10年後 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1年後 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 5 (VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5年後 (VISION)'),
        ),
    ]
