# Generated by Django 4.2.2 on 2024-03-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0029_alter_company_team_action_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfcheckIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfcheck_industry_name', models.CharField(max_length=255, verbose_name='セルフチェック用の業界名称')),
            ],
        ),
        migrations.CreateModel(
            name='SelfcheckRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfcheck_role_name', models.CharField(max_length=100, verbose_name='Selfcheck Role名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(99, '日々研'), (40, 'Partner'), (30, 'Company Admin'), (20, 'Company Super Visor'), (10, 'Company Staff')], unique=True, verbose_name='Role')),
                ('role_name', models.CharField(max_length=100, verbose_name='Role名称')),
                ('selfcheck_roles', models.ManyToManyField(blank=True, related_name='roles', to='hibiLaboSystem.selfcheckrole', verbose_name='Selfcheck Roles')),
            ],
        ),
        migrations.AddField(
            model_name='selfcheckquestion',
            name='selfcheck_industries',
            field=models.ManyToManyField(blank=True, related_name='Selfcheck_questions', to='hibiLaboSystem.selfcheckindustry', verbose_name='業界名称'),
        ),
        migrations.AddField(
            model_name='selfcheckquestion',
            name='selfcheck_roles',
            field=models.ManyToManyField(blank=True, related_name='Selfcheck_questions', to='hibiLaboSystem.selfcheckrole', verbose_name='Selfcheck Roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='hibiLaboSystem.role', verbose_name='役割'),
        ),
    ]
