# Generated by Django 5.0.1 on 2024-02-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0029_alter_company_team_action_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='properties/images'),
        ),
    ]
