# Generated by Django 5.0.1 on 2024-02-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0031_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='', null=True, upload_to='static/assets/images'),
        ),
    ]
