# Generated by Django 4.2.2 on 2024-03-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0031_alter_role_options_alter_selfcheckindustry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='hibiLaboSystem.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='hibiLaboSystem.partner', verbose_name='相棒'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(99, '日々研'), (40, 'Partner'), (30, 'Company Admin'), (20, 'Company SuperVisor'), (10, 'Company Staff')], unique=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hibiLaboSystem.company', verbose_name='会社'),
        ),
        migrations.AlterField(
            model_name='watasheetevaluationperiod',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watasheet_evaluation_periods', to='hibiLaboSystem.company'),
        ),
    ]
