# Generated by Django 4.2.2 on 2024-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0032_alter_branch_company_alter_company_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_action_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (MY ACTION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_action_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (MY ACTION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_action_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (MY ACTION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_concept_1',
            field=models.TextField(blank=True, null=True, verbose_name='My Concept'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_mission_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (MY MISSION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_mission_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (MY MISSION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_mission_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (MY MISSION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_values_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (MY VALUES)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_values_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (MY VALUES)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_values_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (MY VALUES)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_vision_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (MY VISION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_vision_10',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 10 (MY VISION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_vision_10_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10年後 (MY VISION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_vision_1_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1年後 (MY VISION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_vision_5',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 5 (MY VISION)'),
        ),
        migrations.AddField(
            model_name='watasheettyperesult',
            name='my_vision_5_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5年後 (MY VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (TEAM ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_10',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (TEAM ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_10_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10年後 (TEAM ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_1_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1年後 (TEAM ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_5',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (TEAM ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_action_5_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5年後 (TEAM ACTION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_concept_1',
            field=models.TextField(blank=True, null=True, verbose_name='Team Concept'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (TEAM MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (TEAM MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_mission_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (TEAM MISSION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (TEAM VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_2',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (TEAM VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_values_3',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (TEAM VALUES)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 1 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 10 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='10年後 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='1年後 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 5 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5_years',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5年後 (TEAM VISION)'),
        ),
    ]
