# Generated by Django 5.0.3 on 2024-03-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0032_alter_branch_company_alter_company_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role1',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
