# Generated by Django 5.0.3 on 2024-03-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0033_role_role1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role1',
            field=models.CharField(blank=True, choices=[('ROLE_99', '日々研'), ('ROLE_40', 'Partner'), ('ROLE_30', 'Company Admin'), ('ROLE_20', 'Company SuperVisor'), ('ROLE_10', 'Company Staff')], max_length=255, null=True),
        ),
    ]
