# Generated by Django 4.2.2 on 2024-04-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0033_watasheettyperesult_my_action_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_action_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_action_2',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_action_3',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_concept_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_mission_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_mission_2',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_mission_3',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_values_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_values_2',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_values_3',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_vision_1',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_vision_10',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_vision_10_years',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_vision_1_year',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_vision_5',
        ),
        migrations.RemoveField(
            model_name='watasheettyperesult',
            name='my_vision_5_years',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(90, '日々研'), (40, 'Partner'), (30, 'Company Admin'), (20, 'Company SuperVisor'), (10, 'Company Staff')], unique=True, verbose_name='Role'),
        ),
    ]
