# Generated by Django 4.2.3 on 2024-04-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0034_remove_watasheettyperesult_my_action_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_day2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_day3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_day4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_day5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_day6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_day7',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_hour7',
        ),
    ]
