# Generated by Django 5.0.3 on 2024-03-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0035_alter_role_role1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role1',
            field=models.CharField(blank=True, choices=[('Daily_Research', 90), ('Partner', 40), ('Company_Admin', 30), ('Company_SuperVisor', 20), ('Company_Staff', '10')], max_length=255, null=True),
        ),
    ]
