# Generated by Django 4.2.2 on 2024-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0035_remove_user_preferred_day_remove_user_preferred_day2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '支店', 'verbose_name_plural': '支店'},
        ),
        migrations.AlterField(
            model_name='selfcheckquestion',
            name='category_id',
            field=models.IntegerField(blank=True, choices=[(1, '決断力'), (2, '専門性'), (3, '自己管理'), (4, '広報力'), (5, '連携力'), (6, '人間関係'), (7, '対応'), (8, 'チームワーク力'), (9, '総合管理'), (10, '理念浸透'), (11, '自己啓発'), (12, '思考')], null=True),
        ),
    ]
