# Generated by Django 4.2.2 on 2024-04-23 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0037_alter_branch_company_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='team_vision_10_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999, message='最大 3 つの数字のみを入力してください'), django.core.validators.MinValueValidator(1)], verbose_name='10年後 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_1_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999, message='最大 3 つの数字のみを入力してください'), django.core.validators.MinValueValidator(1)], verbose_name='1年後 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999, message='最大 3 つの数字のみを入力してください'), django.core.validators.MinValueValidator(1)], verbose_name='5年後 (TEAM VISION)'),
        ),
    ]
