# Generated by Django 4.2.2 on 2024-04-24 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0038_alter_company_team_vision_10_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watasheettyperesult',
            name='vision_10_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='watasheettyperesult',
            name='vision_1_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='watasheettyperesult',
            name='vision_5_years',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
