# Generated by Django 5.0.3 on 2024-03-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0038_alter_role_role1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role1',
            field=models.CharField(blank=True, choices=[(90, '日々研'), (40, 'Partner'), (30, 'Company_Admin'), (20, 'Company_SuperVisor'), (10, 'Company_Staff')], max_length=255, null=True),
        ),
    ]
