# Generated by Django 5.0.3 on 2024-03-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0039_alter_role_role1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role1',
            field=models.CharField(blank=True, choices=[('日々研', '日々研'), ('Partner', 'Partner'), ('Company_Admin', 'Company Admin'), ('Company_SuperVisor', 'Company SuperVisor'), ('Company_Staff', 'Company Staff')], max_length=255, null=True),
        ),
    ]
