# Generated by Django 4.2.2 on 2024-05-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0039_alter_watasheettyperesult_vision_10_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Branch code'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('code', 'company_id'), name='unique_branch_code'),
        ),
    ]
