# Generated by Django 4.2.2 on 2024-05-08 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0040_branch_code_branch_unique_branch_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelfcheckIndustry',
            new_name='Industry',
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industries', 'verbose_name_plural': 'Industries'},
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='selfcheck_industry_name',
            new_name='industry_name',
        ),
        migrations.RenameField(
            model_name='selfcheckquestion',
            old_name='selfcheck_industries',
            new_name='industries',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_company', to='hibiLaboSystem.industry', verbose_name='業界'),
        ),
        migrations.AlterModelTable(
            name='industry',
            table='industries',
        ),
    ]
