# Generated by Django 4.2.2 on 2024-05-09 06:58

import django.core.files.storage
from django.db import migrations
import hibiLaboSystem.models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0041_rename_selfcheckindustry_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, default='', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=hibiLaboSystem.models.unique_image_filename, verbose_name='アバター'),
        ),
    ]
