# Generated by Django 4.2.2 on 2024-05-10 08:45

import django.core.files.storage
from django.db import migrations, models
import hibiLaboSystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0042_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=hibiLaboSystem.models.unique_image_filename, verbose_name='アバター'),
        ),
    ]
