# Generated by Django 4.2.2 on 2024-05-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0043_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='team_vision_10_years',
        ),
        migrations.RemoveField(
            model_name='company',
            name='team_vision_1_year',
        ),
        migrations.RemoveField(
            model_name='company',
            name='team_vision_5_years',
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_10',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 3 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='team_vision_5',
            field=models.TextField(blank=True, null=True, verbose_name='コンテンツ 2 (TEAM VISION)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='visble_flag',
            field=models.BooleanField(blank=True, default=False, verbose_name='社員名表示'),
        ),
    ]
