# Generated by Django 4.2.2 on 2024-05-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0044_remove_company_team_vision_10_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.IntegerField(choices=[(90, '日々研'), (40, 'Partner'), (30, 'Company Admin'), (20, 'Company SuperVisor'), (10, 'Company Staff'), (25, 'Company Director')], unique=True, verbose_name='Role'),
        ),
    ]
