# Generated by Django 4.2.11 on 2024-07-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0045_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandaraperiod',
            name='input_end_date',
            field=models.DateField(null=True, verbose_name='評価入力終了時間'),
        ),
        migrations.AddField(
            model_name='mandaraperiod',
            name='input_start_date',
            field=models.DateField(null=True, verbose_name='評価入力開始時間'),
        ),
    ]
