# Generated by Django 4.2.11 on 2024-07-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0046_mandaraperiod_input_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandaraperiod',
            name='input_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='評価入力終了時間'),
        ),
        migrations.AlterField(
            model_name='mandaraperiod',
            name='input_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='評価入力開始時間'),
        ),
    ]
