# Generated by Django 4.2.11 on 2024-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiLaboSystem', '0048_alter_bonknowevaluationperiod_evaluation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='romanization_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ローマ字名'),
        ),
    ]
